services:
  app:
    build:
      context: .
      dockerfile: apps/dydx_candle_downloader/Dockerfile
    container_name: dydx_candle_downloader
    command: python -m app.dydx_candle
    ports:
      - 5432:5432
    volumes:
      - ./apps/dydx_candle_downloader:/app
      - ./utils/:/utils
      - ./data:/data
