services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: exchange_data
      TZ: "UTC"
    ports:
      - 5440:5432
    volumes:
      - ./apps/dydx_candle_downloader/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: apps/dydx_candle_downloader/Dockerfile
    container_name: dydx_candle_downloader
    command: python -m app.setup
    volumes:
      - ./apps/dydx_candle_downloader:/app
      - ./utils/:/utils
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy
