services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: dydx_candle_downloader
    command: python ./app/dydx_candle.py
    ports:
      - 5432:5432
    volumes:
      - ./app/:/app
      - ./data:/data
