services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: exchanges_data
      TZ: "UTC"
    ports:
      - 5440:5432
    volumes:
      - ./apps/db_setup/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dydx_candles_setup:
    build:
      context: .
      dockerfile: apps/dydx_candles_downloader/DockerfileSetup
    container_name: dydx_candles_setup
    command: python -m app.setup
    volumes:
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy

  dydx_candles_app:
    build:
      context: .
      dockerfile: apps/dydx_candles_downloader/DockerfileApp
    restart: always
    container_name: dydx_candles_downloader
    command: python -m app.dydx_candles
    volumes:
      - ./data:/data
    depends_on:
      dydx_candles_setup:
        condition: service_completed_successfully
